apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swanlab.cloud.fullname" . }}
  labels:
  {{- include "swanlab.cloud.labels" . | nindent 4 }}
  {{- with (include "swanlab.cloud.annotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ default 0 .Values.service.cloud.replicas }}
  selector:
    matchLabels:
    {{- include "swanlab.cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "swanlab.cloud.labels" . | nindent 8 }}
      {{- with (include "swanlab.cloud.podLabels" . | trim) }}
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "swanlab.cloud.podAnnotations" . | trim) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "swanlab.podSecurityContext" (dict "root" . "securityContext" .Values.service.cloud.securityContext "uid" 101 "gid" 101 "allowPrivilegedPorts" true) | nindent 6 }}
      {{- include "swanlab.podAntiAffinity" (list .Values.global.podAntiAffinityPreset "swanlab.cloud.selectorLabels" . ) | nindent 6 }}
      {{- with (include "swanlab.cloud.nodeSelector" . | trim) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "swanlab.cloud.tolerations" . | trim) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      imagePullSecrets:
      {{- include "swanlab.imagePullSecrets" . | nindent 8 }}
      containers:
        - name: cloud
          image: {{ include "swanlab.cloud.image" . | quote }}
          imagePullPolicy: {{ .Values.service.cloud.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          {{- include "swanlab.containerSecurityContext" (dict "root" . "securityContext" .Values.service.cloud.securityContext) | nindent 10 }}
        {{- if .Values.service.cloud.resources }}
          resources:
        {{- toYaml .Values.service.cloud.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.cloud.fullname" . }}
  labels:
  {{- include "swanlab.cloud.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.cloud.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ include "swanlab.cloud.port" . }}
      targetPort: web
