{{- if .Values.integrations.redis.enabled | eq false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swanlab.redis.fullname" . }}
  labels:
  {{- include "swanlab.redis.labels" . | nindent 4 }}
  {{- with (include "swanlab.redis.annotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
    {{- include "swanlab.redis.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "swanlab.redis.labels" . | nindent 8 }}
      {{- with (include "swanlab.redis.podLabels" . | trim) }}
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "swanlab.redis.podAnnotations" . | trim) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "swanlab.podSecurityContext" (dict "root" . "uid" 1000 "gid" 1000) | nindent 6 }}
      restartPolicy: Always
      imagePullSecrets:
      {{- include "swanlab.imagePullSecrets" . | nindent 8 }}
      {{- with (include "swanlab.redis.nodeSelector" . | trim) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "swanlab.redis.tolerations" . | trim) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: "{{ .Values.dependencies.redis.image.repository }}:{{ .Values.dependencies.redis.image.tag }}"
        imagePullPolicy: {{ .Values.dependencies.redis.image.pullPolicy }}
        ports:
          - containerPort: {{ include "swanlab.redis.port" . }}
            name: redis
        volumeMounts:
          - mountPath: /data
            name: {{ include "swanlab.redis.fullname" . }}-volume
        {{- include "swanlab.containerSecurityContext" (dict "root" .) | nindent 8 }}
        {{- if .Values.dependencies.redis.resources }}
        resources:
        {{- toYaml .Values.dependencies.redis.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: {{ include "swanlab.redis.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "swanlab.redis.pvcName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.redis.fullname" . }}
  labels:
  {{- include "swanlab.redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ include "swanlab.redis.port" . }}
      name: redis
{{- end }}