{{- if .Values.integrations.clickhouse.enabled | eq false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swanlab.clickhouse.fullname" . }}
  labels:
  {{- include "swanlab.clickhouse.labels" . | nindent 4 }}
  {{- with (include "swanlab.clickhouse.annotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
    {{- include "swanlab.clickhouse.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "swanlab.clickhouse.labels" . | nindent 8 }}
      {{- with (include "swanlab.clickhouse.podLabels" . | trim) }}
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "swanlab.clickhouse.podAnnotations" . | trim) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "swanlab.podSecurityContext" (dict "root" . "uid" 101 "gid" 101) | nindent 6 }}
      restartPolicy: Always
      imagePullSecrets:
      {{- include "swanlab.imagePullSecrets" . | nindent 8 }}
      {{- with (include "swanlab.clickhouse.nodeSelector" . | trim) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "swanlab.clickhouse.tolerations" . | trim) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
      - name: clickhouse
        image: "{{ .Values.dependencies.clickhouse.image.repository }}:{{ .Values.dependencies.clickhouse.image.tag }}"
        imagePullPolicy: {{ .Values.dependencies.clickhouse.image.pullPolicy }}
        ports:
          - containerPort: {{ include "swanlab.clickhouse.tcpPort" . }}
            name: clickhouse-tcp
          - containerPort: {{ include "swanlab.clickhouse.httpPort" . }}
            name: clickhouse-http
          {{- if .Values.dependencies.clickhouse.monitor.enable }}
          - containerPort: {{ include "swanlab.clickhouse.metricsPort" . }}
            name: metrics
          {{- end }}
        env:
          - name: TZ
            value: "UTC"
          - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
            value: "1"
          - name: CLICKHOUSE_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "swanlab.clickhouse.secretName" . }}
                key: username
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "swanlab.clickhouse.secretName" . }}
                key: password
        volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: {{ include "swanlab.clickhouse.fullname" . }}-volume
          {{- if .Values.dependencies.clickhouse.monitor.enable }}
          - mountPath: /etc/clickhouse-server/config.d/prometheus.xml
            name: metrics-config
            subPath: prometheus.xml
            readOnly: true
          {{- end }}
        {{- include "swanlab.containerSecurityContext" (dict "root" .) | nindent 8 }}
        {{- if .Values.dependencies.clickhouse.resources }}
        resources:
        {{- toYaml .Values.dependencies.clickhouse.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: {{ include "swanlab.clickhouse.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "swanlab.clickhouse.pvcName" . }}
        {{- if .Values.dependencies.clickhouse.monitor.enable }}
        - name: metrics-config
          configMap:
            name: {{ include "swanlab.clickhouse.fullname" . }}-metrics
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.clickhouse.fullname" . }}
  labels:
  {{- include "swanlab.clickhouse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.clickhouse.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ include "swanlab.clickhouse.tcpPort" . }}
      name: clickhouse-tcp
    - port: {{ include "swanlab.clickhouse.httpPort" . }}
      name: clickhouse-http
{{- end }}
