name: 'Helm Chart Lint'

on:
  # 当提交代码到 main 分支且 charts 目录有更改时触发
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  # 当发起 PR 合并到 main 分支且 charts 目录有更改时触发（推荐加上，方便在合并前拦截错误）
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

# 允许同时运行一个作业，并取消旧的作业
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    # 仅需只读权限即可进行 Lint 检查
    permissions:
      contents: read

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        # Lint 阶段不需要完整的 Git 历史，默认的 fetch-depth: 1 即可，这样速度更快

      - name: 🛠️ Set up Helm
        uses: azure/setup-helm@v4.3.0
        
      - name: 📥 Add Traefik Helm Repo
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo update

      - name: 🦢 Add SwanLab Helm Repo
        run: |
          helm repo add swanlab https://helm.swanlab.cn
          helm repo update

      - name: 🔍 Run Helm Lint
        run: |
          find ./charts -maxdepth 1 -mindepth 1 -type d | while read chart_dir; do
            echo "Linting $chart_dir..."
            helm dependency update "$chart_dir"
            helm lint "$chart_dir"
          done